services:
  frontend:
    build:
      context: ./client
    ports:
      - "8080:80"
    volumes:
      - ./client/html:/usr/share/nginx/html
      - ./client/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    restart: always

  backend:
    env_file:
      - ./api/.env
    build:
      context: ./api
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./api:/app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - HOST=0.0.0.0
    depends_on:
      - db
    restart: always
    command: sh -c "npm install && npm run migrate && npm run seed && npm run start"

  db:
    env_file:
      - ./api/.env
    image: postgres:13-alpine
    ports:
      - "${DB_PORT:-5454}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
